#!/bin/sh
config_file=./config.h
if n=$(nproc 2>/dev/null || sysctl -n hw.logicalcpu 2>/dev/null || getconf _NPROCESESORS_ONLN 2>/dev/null); then
	echo "$(sed "s/#define MAX_FORKS[[:space:]]*.*[[:space:]]*$/#define MAX_FORKS $n/" $config_file)" > $config_file
else
	echo "Can't get number of CPU cores!"
fi